spring:
    datasource:
      driverClassName : com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/fixedasset?useUnicode=true&characterEncoding=utf8&autoReconnect=true
      username: fa
      password: 123456
    thymeleaf:
      cache: false
      mode: LEGACYHTML5
      content-type: text/html; charset=utf-8
    profiles:
      active: dev
      
mybatis:
    type-aliases-package: com.xj2.fixed.model
    config-location: classpath:mybatis.xml
    mapper-locations: classpath:mybatis/mapper/*.xml
#    configuration:
#      lazy-loading-enabled: true
logging:
  level:
    org.springframework.security: INFO
    org.mybatis: INFO
    org.springframework: INFO
    org.spring.springboot.dao: INFO
    com.fixed.asset.mapper : debug


